universe = vanilla
log =./logs/helloworld_$(Cluster).log
error = ./logs/helloworld_$(Cluster)_$(Process).err
output = ./logs/helloworld$(Cluster)_$(Process).out


executable = helloworld.sh
arguments = $(Process)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = output



request_cpus = 1
request_memory = 1GB
request_disk = 1MB
#
# Tell HTCondor to run 3 instances of our job:
queue 3
